"""Add medications table with timezone

Revision ID: 3f378a035dd5
Revises:
Create Date: 2026-01-23 01:04:40.514301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f378a035dd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='UTC'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'timezone')
    # ### end Alembic commands ###
