"""Sync schema

Revision ID: 4e0179c9b4d1
Revises: 59e231269631
Create Date: 2026-01-28 23:58:47.746430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e0179c9b4d1'
down_revision: Union[str, Sequence[str], None] = '59e231269631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_logs', sa.Column('action', sa.Enum('TAKEN', 'SKIPPED', 'MISSED', name='logaction', native_enum=False), nullable=False))
    op.alter_column('medications', 'reminder_times',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of times for daily reminders, stored as comma-separated values',
               existing_nullable=True)
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('medications', 'reminder_times',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of times for daily reminders, stored as comma-separated values',
               existing_nullable=True)
    op.drop_column('medication_logs', 'action')
    # ### end Alembic commands ###
