"""Add reminder_times json column

Revision ID: 7691679c0781
Revises: 5f6c05e902aa
Create Date: 2026-01-26 04:01:46.711113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api.src.medications.models import TimeList


# revision identifiers, used by Alembic.
revision: str = '7691679c0781'
down_revision: Union[str, Sequence[str], None] = '5f6c05e902aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ...
    op.add_column(
        'medication_logs', # (Double check: Did you mean to add this to 'medications'?)
        sa.Column(
            'reminder_times',
            TimeList(), # <--- CHANGE THIS (Remove the long 'api.src...' prefix)
            nullable=True,
            comment='List of times...'
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('medications', 'reminder_times')
    # op.drop_column('medication_logs', 'reminder_times')
    # # ### end Alembic commands ###
