"""add medication logs

Revision ID: 88aa7fa2a565
Revises: 
Create Date: 2026-02-14 08:22:26.235701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88aa7fa2a565'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_logs', sa.Column('medication_name_snapshot', sa.String(length=255), nullable=False, comment='Name of medication at the time of intake'))
    op.add_column('medication_logs', sa.Column('dosage_snapshot', sa.String(length=100), nullable=True, comment='Dosage strength at the time of intake'))
    op.add_column('medication_logs', sa.Column('source', sa.Enum('MANUAL', 'NOTIFICATION', 'WEARABLE', 'IMPORT', 'API', name='logsource', native_enum=False), nullable=False))
    op.add_column('medication_logs', sa.Column('is_voided', sa.Boolean(), nullable=False, comment="True if this log entry was made in error and 'deleted' by user"))
    op.add_column('medication_logs', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('medication_logs', 'medication_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_med_logs_user_taken', 'medication_logs', ['user_id', 'taken_at'], unique=False)
    op.create_foreign_key(None, 'medication_logs', 'medications', ['medication_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reminders', 'medications', ['medication_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_constraint(None, 'medication_logs', type_='foreignkey')
    op.drop_index('idx_med_logs_user_taken', table_name='medication_logs')
    op.alter_column('medication_logs', 'medication_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('medication_logs', 'voided_at')
    op.drop_column('medication_logs', 'is_voided')
    op.drop_column('medication_logs', 'source')
    op.drop_column('medication_logs', 'dosage_snapshot')
    op.drop_column('medication_logs', 'medication_name_snapshot')
    # ### end Alembic commands ###
