"""Add administration_route

Revision ID: b3d5eeee5e84
Revises: 3f378a035dd5
Create Date: 2026-01-23 12:16:39.418428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d5eeee5e84'
down_revision: Union[str, Sequence[str], None] = '3f378a035dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('administration_route', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'administration_route')
    # ### end Alembic commands ###
